<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bataille [
<!ELEMENT Bataille (Humain, IA, Epoque, Courant)>
<!ELEMENT Humain (attaqueRates, attaqueTouches, bateaux)>
<!ELEMENT attaqueRates (attaque*)>
<!ELEMENT attaqueTouches (attaque*)>
<!ELEMENT attaque (x, y)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT bateaux (bateau*)>
<!ELEMENT bateau (type, hp, Positions)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT hp (#PCDATA)>
<!ELEMENT Positions (Position+)>
<!ELEMENT Position (x, y)>
<!ELEMENT IA (type, attaqueRates, attaqueTouches, bateaux)>
<!ELEMENT Epoque (#PCDATA)>
<!ELEMENT Courant (#PCDATA)>
] >
<Bataille>
<Humain>
<attaqueRates>
</attaqueRates>
<attaqueTouches>
</attaqueTouches>
<bateaux>
<bateau>
<type>ManOWar</type>
<hp>30</hp>
<Positions>
<Position>
<x>1</x>
<y>9</y>
</Position>
<Position>
<x>1</x>
<y>8</y>
</Position>
<Position>
<x>1</x>
<y>7</y>
</Position>
<Position>
<x>1</x>
<y>6</y>
</Position>
<Position>
<x>1</x>
<y>5</y>
</Position>
</Positions>
</bateau>
<bateau>
<type>Galion</type>
<hp>20</hp>
<Positions>
<Position>
<x>8</x>
<y>7</y>
</Position>
<Position>
<x>7</x>
<y>7</y>
</Position>
<Position>
<x>6</x>
<y>7</y>
</Position>
<Position>
<x>5</x>
<y>7</y>
</Position>
</Positions>
</bateau>
<bateau>
<type>Drakkar</type>
<hp>15</hp>
<Positions>
<Position>
<x>9</x>
<y>1</y>
</Position>
<Position>
<x>8</x>
<y>1</y>
</Position>
</Positions>
</bateau>
<bateau>
<type>Caravelle</type>
<hp>10</hp>
<Positions>
<Position>
<x>0</x>
<y>2</y>
</Position>
<Position>
<x>1</x>
<y>2</y>
</Position>
<Position>
<x>2</x>
<y>2</y>
</Position>
</Positions>
</bateau>
<bateau>
<type>Caravelle</type>
<hp>10</hp>
<Positions>
<Position>
<x>4</x>
<y>4</y>
</Position>
<Position>
<x>5</x>
<y>4</y>
</Position>
<Position>
<x>6</x>
<y>4</y>
</Position>
</Positions>
</bateau>
</bateaux>
</Humain>
<IA>
<type>0</type>
<attaqueRates>
</attaqueRates>
<attaqueTouches>
</attaqueTouches>
<bateaux>
<bateau>
<type>ManOWar</type>
<hp>30</hp>
<Positions>
<Position>
<x>4</x>
<y>7</y>
</Position>
<Position>
<x>4</x>
<y>6</y>
</Position>
<Position>
<x>4</x>
<y>5</y>
</Position>
<Position>
<x>4</x>
<y>4</y>
</Position>
<Position>
<x>4</x>
<y>3</y>
</Position>
</Positions>
</bateau>
<bateau>
<type>Galion</type>
<hp>20</hp>
<Positions>
<Position>
<x>5</x>
<y>5</y>
</Position>
<Position>
<x>5</x>
<y>6</y>
</Position>
<Position>
<x>5</x>
<y>7</y>
</Position>
<Position>
<x>5</x>
<y>8</y>
</Position>
</Positions>
</bateau>
<bateau>
<type>Drakkar</type>
<hp>15</hp>
<Positions>
<Position>
<x>0</x>
<y>5</y>
</Position>
<Position>
<x>0</x>
<y>6</y>
</Position>
</Positions>
</bateau>
<bateau>
<type>Caravelle</type>
<hp>10</hp>
<Positions>
<Position>
<x>3</x>
<y>4</y>
</Position>
<Position>
<x>3</x>
<y>3</y>
</Position>
<Position>
<x>3</x>
<y>2</y>
</Position>
</Positions>
</bateau>
<bateau>
<type>Caravelle</type>
<hp>10</hp>
<Positions>
<Position>
<x>1</x>
<y>7</y>
</Position>
<Position>
<x>2</x>
<y>7</y>
</Position>
<Position>
<x>3</x>
<y>7</y>
</Position>
</Positions>
</bateau>
</bateaux>
</IA>
<Epoque>0</Epoque>
<Courant>0</Courant>
</Bataille>
