<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Bataille
  [
    <!ELEMENT Bataille (Humain, IA, Epoque, Courant)>
    <!ELEMENT Humain (attaques, bateaux)>
    <!ELEMENT attaques (attaque*)>
    <!ELEMENT attaque (x, y)>
    <!ELEMENT x (#PCDATA)>
    <!ELEMENT y (#PCDATA)>
    <!ELEMENT bateaux (bateau*)>
    <!ELEMENT bateau (type, hp, Positions)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT hp (#PCDATA)>
    <!ELEMENT Positions (Position+)>
    <!ELEMENT Position (x, y)>
    <!ELEMENT IA (type, attaques, bateaux)>
    <!ELEMENT Epoque (#PCDATA)>
    <!ELEMENT Courant (#PCDATA)>
  ]
  >
<Bataille>
    <Humain>
      <attaques>
        <attaque>
          <x>1</x>
          <y>1</y>
        </attaque>
        <attaque>
          <x>5</x>
          <y>2</y>
        </attaque>
      </attaques>
      <bateaux>
        <bateau>
          <type>Torpilleur</type>
          <hp>20</hp>
          <Positions>
            <Position>
              <x>5</x>
              <y>4</y>
            </Position>
            <Position>
              <x>5</x>
              <y>5</y>
            </Position>
          </Positions>
        </bateau>
      </bateaux>
    </Humain>
    <IA>
      <type>0</type>
      <attaques></attaques>
      <bateaux></bateaux>
    </IA>
    <Epoque>1</Epoque>
    <Courant>0</Courant>
</Bataille>